// src/galgame/components/layout/QuickAccessMenu.vue
<template>
  <!-- Left top menu -->
  <div ref="leftRef" class="absolute" :style="leftMenuStyle">
    <div class="flex flex-col" :style="quickMenuStackStyle">
      <template v-if="!store.leftMenuExpanded">
        <SkinShell :skin="leftCollapsedSkin" :hovered="leftCollapsedHovered" :active="leftCollapsedActive">
          <button
            class="flex cursor-pointer items-center justify-center border backdrop-blur-sm transition-all duration-200"
            :style="leftCollapsedSkin ? skinnedIconButtonStyle : btnIconStyle"
            @click="store.toggleLeftMenu()"
            @mouseenter="leftCollapsedHovered = true"
            @mouseleave="
              leftCollapsedHovered = false;
              leftCollapsedActive = false;
            "
            @mousedown="leftCollapsedActive = true"
            @mouseup="leftCollapsedActive = false"
          >
            <i class="fa-solid fa-user" :style="leftCollapsedIconStyle" />
          </button>
        </SkinShell>
      </template>
      <template v-else>
        <div class="animate-fade-in-up flex flex-col" :style="leftExpandedStackStyle">
          <CapsuleButton
            icon="fa-user"
            label="角色"
            icon-side="left"
            :skin-key="LEFT_EXPANDED_SKIN_KEY"
            @click="store.setOverlay('character')"
          />
          <CapsuleButton
            icon="fa-gamepad"
            label="玩法"
            icon-side="left"
            :skin-key="LEFT_EXPANDED_SKIN_KEY"
            @click="store.setOverlay('gameplay')"
          />
        </div>
      </template>
    </div>
  </div>

  <!-- Right top menu -->
  <div ref="rightRef" class="absolute" :style="rightMenuStyle">
    <div class="flex flex-col items-end" :style="quickMenuStackStyle">
      <template v-if="!store.rightMenuExpanded">
        <SkinShell :skin="rightCollapsedSkin" :hovered="rightCollapsedHovered" :active="rightCollapsedActive">
          <button
            class="flex cursor-pointer items-center justify-center border backdrop-blur-sm transition-all duration-200"
            :style="rightCollapsedSkin ? skinnedIconButtonStyle : btnIconStyle"
            @click="store.toggleRightMenu()"
            @mouseenter="rightCollapsedHovered = true"
            @mouseleave="
              rightCollapsedHovered = false;
              rightCollapsedActive = false;
            "
            @mousedown="rightCollapsedActive = true"
            @mouseup="rightCollapsedActive = false"
          >
            <i class="fa-solid fa-gear" :style="rightCollapsedIconStyle" />
          </button>
        </SkinShell>
      </template>
      <template v-else>
        <div class="animate-fade-in-up flex flex-col items-end" :style="rightExpandedStackStyle">
          <CapsuleButton
            icon="fa-gear"
            label="设置"
            icon-side="right"
            :skin-key="RIGHT_EXPANDED_SKIN_KEY"
            @click="store.setOverlay('settings')"
          />
          <CapsuleButton
            :icon="isFullscreen ? 'fa-compress' : 'fa-expand'"
            :label="isFullscreen ? '退出全屏' : '全屏'"
            icon-side="right"
            :skin-key="RIGHT_EXPANDED_SKIN_KEY"
            @click="$emit('toggle-fullscreen')"
          />
          <CapsuleButton
            icon="fa-book-open"
            label="历史"
            icon-side="right"
            :skin-key="RIGHT_EXPANDED_SKIN_KEY"
            @click="store.setOverlay('history')"
          />
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import CapsuleButton from '../common/CapsuleButton.vue';
import SkinShell from '../common/SkinShell.vue';
import { useVNStore } from '../../store';

const LEFT_EXPANDED_SKIN_KEY = 'quickMenuExpandedLeft';
const RIGHT_EXPANDED_SKIN_KEY = 'quickMenuExpandedRight';

defineProps<{
  isFullscreen: boolean;
}>();

defineEmits<{ 'toggle-fullscreen': [] }>();

const store = useVNStore();
const leftRef = ref<HTMLDivElement | null>(null);
const rightRef = ref<HTMLDivElement | null>(null);
const leftCollapsedHovered = ref(false);
const leftCollapsedActive = ref(false);
const rightCollapsedHovered = ref(false);
const rightCollapsedActive = ref(false);

const leftCollapsedSkin = computed(() => store.getComponentSkinForCurrent('quickMenuCollapsedLeft'));
const rightCollapsedSkin = computed(() => store.getComponentSkinForCurrent('quickMenuCollapsedRight'));

const leftMenuStyle = {
  top: 'var(--theme-quick-menu-left-top, var(--theme-quick-menu-top, 1rem))',
  left: 'var(--theme-quick-menu-left, 1rem)',
  zIndex: '40',
};
const rightMenuStyle = {
  top: 'var(--theme-quick-menu-right-top, var(--theme-quick-menu-top, 1rem))',
  right: 'var(--theme-quick-menu-right, 1rem)',
  zIndex: '40',
};
const quickMenuStackStyle = {
  gap: 'var(--theme-quick-menu-gap, 0.62rem)',
};
const leftExpandedStackStyle = {
  gap: 'var(--theme-quick-menu-gap, 0.62rem)',
};
const rightExpandedStackStyle = {
  gap: 'var(--theme-quick-menu-gap, 0.62rem)',
};

const btnIconStyle = {
  width: 'var(--theme-quick-menu-collapsed-button-size, 2rem)',
  height: 'var(--theme-quick-menu-collapsed-button-size, 2rem)',
  borderColor: 'rgba(90,79,64,0.5)',
  background: 'var(--theme-button-bg, var(--vn-panel-bg))',
  color: 'var(--theme-accent-soft, rgba(139,69,19,0.7))',
  borderRadius: '2px',
  backdropFilter: 'blur(var(--theme-button-content-blur, 0px)) saturate(var(--theme-button-content-saturate, 100%))',
};

const skinnedIconButtonStyle = {
  width: '100%',
  height: '100%',
  padding: '0',
  borderColor: 'transparent',
  background: 'var(--theme-button-bg, transparent)',
  color: 'rgba(139,69,19,0.78)',
  borderRadius: '0px',
  backdropFilter: 'blur(var(--theme-button-content-blur, 0px)) saturate(var(--theme-button-content-saturate, 100%))',
};

const leftCollapsedIconStyle = {
  fontSize: 'var(--theme-quick-menu-left-collapsed-icon-size, var(--theme-quick-menu-icon-size, 0.875rem))',
  transform:
    'translate(var(--theme-quick-menu-left-collapsed-icon-translate-x, var(--theme-quick-menu-collapsed-icon-translate-x, 0px)), var(--theme-quick-menu-left-collapsed-icon-translate-y, var(--theme-quick-menu-collapsed-icon-translate-y, 0px)))',
};

const rightCollapsedIconStyle = {
  fontSize: 'var(--theme-quick-menu-right-collapsed-icon-size, var(--theme-quick-menu-icon-size, 0.875rem))',
  transform:
    'translate(var(--theme-quick-menu-right-collapsed-icon-translate-x, var(--theme-quick-menu-collapsed-icon-translate-x, 0px)), var(--theme-quick-menu-right-collapsed-icon-translate-y, var(--theme-quick-menu-collapsed-icon-translate-y, 0px)))',
};

function handleClickOutside(e: MouseEvent) {
  if (store.leftMenuExpanded && leftRef.value && !leftRef.value.contains(e.target as Node)) store.toggleLeftMenu();
  if (store.rightMenuExpanded && rightRef.value && !rightRef.value.contains(e.target as Node)) store.toggleRightMenu();
}

onMounted(() => document.addEventListener('mousedown', handleClickOutside));
onUnmounted(() => document.removeEventListener('mousedown', handleClickOutside));
</script>

// 参考/b_jk0UQt1GzDw-1772092920729/components/vn/quick-access-menu.tsx
"use client"

import { useVN, useVNActions } from "@/lib/vn-store"
import { useState, useEffect, useRef } from "react"
import { User, Gamepad2, Settings, Maximize, BookOpen } from "lucide-react"

function CapsuleButton({
  icon,
  label,
  onClick,
  iconSide = "left",
}: {
  icon: React.ReactNode
  label: string
  onClick: () => void
  iconSide?: "left" | "right"
}) {
  return (
    <button
      onClick={onClick}
      className="flex items-center gap-2 px-3 py-1.5 border border-border/50 bg-[var(--vn-panel-bg)] backdrop-blur-sm
        hover:bg-foreground/10 hover:border-rust/40 transition-all duration-200 cursor-pointer
        text-foreground/80 hover:text-foreground group"
      style={{ borderRadius: "2px" }}
    >
      {iconSide === "left" && (
        <span className="text-rust/70 group-hover:text-rust transition-colors">{icon}</span>
      )}
      <span className="text-xs font-serif tracking-wider whitespace-nowrap">{label}</span>
      {iconSide === "right" && (
        <span className="text-rust/70 group-hover:text-rust transition-colors">{icon}</span>
      )}
    </button>
  )
}

export function QuickAccessMenu() {
  const { state } = useVN()
  const { toggleLeftMenu, toggleRightMenu, setOverlay } = useVNActions()
  const leftRef = useRef<HTMLDivElement>(null)
  const rightRef = useRef<HTMLDivElement>(null)

  // Close menus when clicking outside
  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (
        state.leftMenuExpanded &&
        leftRef.current &&
        !leftRef.current.contains(e.target as Node)
      ) {
        toggleLeftMenu()
      }
      if (
        state.rightMenuExpanded &&
        rightRef.current &&
        !rightRef.current.contains(e.target as Node)
      ) {
        toggleRightMenu()
      }
    }

    document.addEventListener("mousedown", handleClickOutside)
    return () => document.removeEventListener("mousedown", handleClickOutside)
  }, [state.leftMenuExpanded, state.rightMenuExpanded, toggleLeftMenu, toggleRightMenu])

  const handleFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen()
    } else {
      document.exitFullscreen()
    }
  }

  return (
    <>
      {/* Left top menu */}
      <div ref={leftRef} className="absolute top-4 left-4 z-40">
        <div className="flex flex-col gap-1.5">
          {/* Button 1: always visible as icon-only when collapsed */}
          {!state.leftMenuExpanded ? (
            <button
              onClick={toggleLeftMenu}
              className="w-8 h-8 flex items-center justify-center border border-border/50 bg-[var(--vn-panel-bg)] backdrop-blur-sm
                hover:bg-foreground/10 hover:border-rust/40 transition-all duration-200 cursor-pointer text-rust/70 hover:text-rust"
              style={{ borderRadius: "2px" }}
              aria-label="Expand menu"
            >
              <User className="w-4 h-4" />
            </button>
          ) : (
            <div className="flex flex-col gap-1.5 animate-fade-in-up">
              <CapsuleButton
                icon={<User className="w-3.5 h-3.5" />}
                label="角色"
                onClick={() => setOverlay("character")}
                iconSide="left"
              />
              <CapsuleButton
                icon={<Gamepad2 className="w-3.5 h-3.5" />}
                label="玩法"
                onClick={() => setOverlay("gameplay")}
                iconSide="left"
              />
            </div>
          )}
        </div>
      </div>

      {/* Right top menu */}
      <div ref={rightRef} className="absolute top-4 right-4 z-40">
        <div className="flex flex-col gap-1.5 items-end">
          {!state.rightMenuExpanded ? (
            <button
              onClick={toggleRightMenu}
              className="w-8 h-8 flex items-center justify-center border border-border/50 bg-[var(--vn-panel-bg)] backdrop-blur-sm
                hover:bg-foreground/10 hover:border-rust/40 transition-all duration-200 cursor-pointer text-rust/70 hover:text-rust"
              style={{ borderRadius: "2px" }}
              aria-label="Expand menu"
            >
              <Settings className="w-4 h-4" />
            </button>
          ) : (
            <div className="flex flex-col gap-1.5 items-end animate-fade-in-up">
              <CapsuleButton
                icon={<Settings className="w-3.5 h-3.5" />}
                label="设置"
                onClick={() => setOverlay("settings")}
                iconSide="right"
              />
              <CapsuleButton
                icon={<Maximize className="w-3.5 h-3.5" />}
                label="全屏"
                onClick={handleFullscreen}
                iconSide="right"
              />
              <CapsuleButton
                icon={<BookOpen className="w-3.5 h-3.5" />}
                label="历史"
                onClick={() => setOverlay("history")}
                iconSide="right"
              />
            </div>
          )}
        </div>
      </div>
    </>
  )
}
