// 参考/b_jk0UQt1GzDw-1772092920729/components/vn/history-panel.tsx
"use client"

import { useVN, useVNActions } from "@/lib/vn-store"
import { X } from "lucide-react"
import { useRef, useEffect } from "react"

export function HistoryPanel() {
  const { state } = useVN()
  const { setOverlay, goToLine } = useVNActions()
  const scrollRef = useRef<HTMLDivElement>(null)

  // Auto-scroll to current line
  useEffect(() => {
    if (scrollRef.current) {
      const currentEl = scrollRef.current.querySelector(`[data-line="${state.currentLineIndex}"]`)
      if (currentEl) {
        currentEl.scrollIntoView({ block: "center", behavior: "smooth" })
      }
    }
  }, [state.currentLineIndex])

  // Only show lines up to currentLineIndex
  const visibleLines = state.dialogueHistory.slice(0, state.currentLineIndex + 1)

  return (
    <div className="absolute inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-ink/70 backdrop-blur-sm" onClick={() => setOverlay("none")} />

      {/* Panel */}
      <div className="relative w-full max-w-2xl max-h-[85vh] mx-4 border border-border/60 bg-[var(--vn-panel-bg)] backdrop-blur-md overflow-hidden animate-fade-in-up">
        {/* Header decoration */}
        <div className="h-[3px] bg-gradient-to-r from-transparent via-rust/60 to-transparent" />
        <div className="h-[1px] mt-[1px] bg-gradient-to-r from-transparent via-rust/30 to-transparent" />

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border/30">
          <div className="flex items-center gap-3">
            <div className="stamp-effect">
              <span className="text-rust text-xs font-bold tracking-widest">LOG</span>
            </div>
            <h2 className="text-lg font-bold tracking-widest text-foreground/90">历史记录</h2>
          </div>
          <button
            onClick={() => setOverlay("none")}
            className="w-8 h-8 flex items-center justify-center text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
            aria-label="Close history"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Newspaper-style column header */}
        <div className="px-6 py-2 border-b border-border/20 flex items-center">
          <div className="text-[9px] text-muted-foreground font-mono tracking-wider">
            {'--- 对话记录 · 第一章 ---'}
          </div>
          <div className="flex-1" />
          <div className="text-[9px] text-muted-foreground font-mono">
            共 {visibleLines.length} 条
          </div>
        </div>

        {/* History list */}
        <div
          ref={scrollRef}
          className="px-6 py-4 overflow-y-auto no-scrollbar max-h-[calc(85vh-130px)]"
        >
          {visibleLines.map((line, index) => {
            const isCurrent = index === state.currentLineIndex

            return (
              <div
                key={line.id}
                data-line={index}
                onClick={() => {
                  goToLine(index)
                  setOverlay("none")
                }}
                className={`py-2.5 border-b border-border/10 cursor-pointer transition-colors duration-150 hover:bg-foreground/5 ${
                  isCurrent ? "bg-rust/10 border-rust/20" : ""
                }`}
              >
                <div className="flex items-start gap-3">
                  {/* Line number */}
                  <span className="text-[9px] text-muted-foreground/50 font-mono w-6 text-right shrink-0 pt-0.5">
                    {String(index + 1).padStart(3, "0")}
                  </span>

                  <div className="flex-1 min-w-0">
                    {line.speaker ? (
                      <>
                        {/* Speaker name */}
                        <span className="text-rust text-xs font-bold tracking-wider">
                          {line.speaker}
                        </span>
                        {/* Dialogue text */}
                        <p className="text-sm text-foreground/80 mt-0.5 leading-relaxed">
                          {line.text}
                        </p>
                      </>
                    ) : (
                      /* Narration - indent 2 chars when no speaker */
                      <p className="text-sm text-foreground/60 italic leading-relaxed pl-[2em]">
                        {line.text}
                      </p>
                    )}
                  </div>

                  {/* Current marker */}
                  {isCurrent && (
                    <div className="w-1.5 h-1.5 bg-rust rotate-45 mt-1.5 shrink-0" />
                  )}
                </div>
              </div>
            )
          })}
        </div>

        {/* Bottom decoration */}
        <div className="h-[1px] bg-gradient-to-r from-transparent via-rust/30 to-transparent" />
        <div className="h-[2px] mt-[1px] bg-gradient-to-r from-transparent via-rust/50 to-transparent" />
      </div>
    </div>
  )
}

// src/galgame/components/panel/HistoryPanel.vue
<template>
  <div data-ui="history-panel" class="absolute inset-0 flex items-center justify-center px-4" style="z-index: 50">
    <div
      data-ui="panel-backdrop"
      class="absolute inset-0"
      :style="{
        background: 'var(--theme-panel-backdrop, rgba(42, 36, 32, 0.7))',
        backdropFilter: 'blur(var(--theme-panel-backdrop-blur, 4px))',
      }"
      @click="store.setOverlay('none')"
    />

    <SkinShell :skin="historyPanelSkin" :shell-style="panelShellStyle">
      <div
        data-ui="panel"
        class="animate-fade-in-up relative flex w-full flex-col overflow-hidden border"
        :style="
          historyPanelSkin ? { ...panelStyle, borderColor: 'transparent', background: 'transparent' } : panelStyle
        "
      >
        <div :style="decoTop" />
        <div :style="decoTopThin" />

        <!-- Header -->
        <div class="flex items-center justify-between px-6 py-4" :style="headerBorder">
          <div class="flex items-center gap-3">
            <div class="stamp-effect">
              <span
                style="
                  color: var(--theme-accent, var(--rust));
                  font-size: 0.75rem;
                  font-weight: bold;
                  letter-spacing: 0.15em;
                "
                >LOG</span
              >
            </div>
            <h2
              class="text-lg font-bold tracking-widest"
              style="color: var(--theme-text-main, rgba(212, 197, 160, 0.9))"
            >
              历史记录
            </h2>
          </div>
          <button
            class="flex h-8 w-8 cursor-pointer items-center justify-center"
            style="color: var(--theme-text-muted, var(--vn-muted))"
            @click="store.setOverlay('none')"
          >
            <i class="fa-solid fa-xmark" />
          </button>
        </div>

        <!-- Pagination bar: floor navigation -->
        <div
          class="flex items-center gap-3 px-6 py-2"
          :style="{ borderBottom: '1px solid var(--theme-history-header-border, rgba(90,79,64,0.2))' }"
        >
          <button
            class="flex h-6 w-6 cursor-pointer items-center justify-center transition-colors"
            :style="{
              color: previewIndex > 0 ? 'var(--theme-text-muted)' : 'var(--theme-text-faint, rgba(139,125,107,0.3))',
            }"
            :disabled="previewIndex <= 0"
            @click="prevPage"
          >
            <i class="fa-solid fa-chevron-left text-xs" />
          </button>
          <input
            type="number"
            :value="previewIndex + 1"
            :min="1"
            :max="totalFloors"
            class="w-12 bg-transparent text-center outline-none"
            style="
              color: var(--theme-history-info-color, var(--theme-text-muted));
              font-size: 9px;
              font-family: monospace;
            "
            @change="onPageInput"
            @keydown.enter.prevent="onPageInput"
          />
          <span
            style="
              font-size: 9px;
              color: var(--theme-history-info-color, var(--theme-text-muted));
              font-family: monospace;
            "
          >
            / {{ totalFloors }}
          </span>
          <button
            class="flex h-6 w-6 cursor-pointer items-center justify-center transition-colors"
            :style="{
              color:
                previewIndex < totalFloors - 1
                  ? 'var(--theme-text-muted)'
                  : 'var(--theme-text-faint, rgba(139,125,107,0.3))',
            }"
            :disabled="previewIndex >= totalFloors - 1"
            @click="nextPage"
          >
            <i class="fa-solid fa-chevron-right text-xs" />
          </button>
          <button
            class="ml-auto cursor-pointer px-3 py-1 text-xs transition-colors"
            style="color: var(--theme-accent)"
            @click="jumpToFloor"
          >
            跳转到此楼层
          </button>
        </div>

        <!-- Info bar: block count of current preview floor -->
        <div
          class="flex items-center px-6 py-2"
          :style="{ borderBottom: '1px solid var(--theme-history-header-border, rgba(90,79,64,0.2))' }"
        >
          <div
            style="
              font-size: 9px;
              color: var(--theme-history-info-color, var(--theme-text-muted, var(--vn-muted)));
              font-family: monospace;
            "
          >
            共 {{ historyLines.length }} 条
          </div>
        </div>

        <!-- Dialogue list -->
        <div ref="scrollRef" class="no-scrollbar min-h-0 flex-1 overflow-y-auto px-6 py-4">
          <div
            v-for="(line, index) in historyLines"
            :key="index"
            :data-line="index"
            class="cursor-pointer py-2.5 transition-colors duration-150"
            :style="{
              borderBottom: '1px solid var(--theme-history-row-border, rgba(90,79,64,0.1))',
              background:
                index === previewIndex ? 'var(--theme-history-active-bg, rgba(139,69,19,0.1))' : 'transparent',
            }"
            @click="goToLine(index)"
          >
            <div class="flex items-start gap-3">
              <span
                class="shrink-0 pt-0.5 text-right"
                style="
                  font-size: 9px;
                  color: var(--theme-history-index-color, var(--theme-text-faint, rgba(139, 125, 107, 0.5)));
                  font-family: monospace;
                  width: 1.5rem;
                "
              >
                {{ String(index + 1).padStart(3, '0') }}
              </span>
              <div class="min-w-0 flex-1">
                <template v-if="line.speaker">
                  <span
                    style="
                      color: var(--theme-history-speaker-color, var(--theme-accent, var(--rust)));
                      font-size: 0.75rem;
                      font-weight: bold;
                      letter-spacing: 0.1em;
                    "
                    >{{ line.speaker }}</span
                  >
                  <p
                    class="mt-0.5 text-sm leading-relaxed"
                    style="color: var(--theme-history-text-color, var(--theme-text-soft, rgba(212, 197, 160, 0.8)))"
                  >
                    {{ line.text }}
                  </p>
                </template>
                <p
                  v-else
                  class="text-sm leading-relaxed italic"
                  style="color: var(--theme-history-narration-color, rgba(212, 197, 160, 0.6)); padding-left: 2em"
                >
                  {{ line.text }}
                </p>
              </div>
              <div
                v-if="index === previewIndex"
                class="mt-1.5 shrink-0"
                style="width: 6px; height: 6px; background: var(--theme-accent, var(--rust)); transform: rotate(45deg)"
              />
            </div>
          </div>
          <div
            v-if="historyLines.length === 0"
            class="py-8 text-center"
            style="color: var(--theme-text-muted, var(--vn-muted)); font-size: 0.75rem"
          >
            暂无对话记录
          </div>
        </div>

        <div :style="decoBottomThin" />
        <div :style="decoBottom" />
      </div>
    </SkinShell>
  </div>
</template>

<script setup lang="ts">
import SkinShell from '../common/SkinShell.vue';
import { useVNStore } from '../../store';
import type { MessageBlock } from '../../types/message';

const emit = defineEmits<{
  goToLine: [index: number];
}>();

const store = useVNStore();
const scrollRef = ref<HTMLDivElement | null>(null);

const historyPanelSkin = computed(() => store.getComponentSkinForCurrent('historyPanel'));

// 可见楼层索引（跳过 user 和隐藏楼层）
const visibleFloorIndices = computed(() => {
  return store.dialogues
    .map((unit, i) => ({ unit, i }))
    .filter(({ unit }) => unit.role !== 'user' && !unit.isHidden)
    .map(({ i }) => i);
});

const totalFloors = computed(() => visibleFloorIndices.value.length);
// 当前预览楼层在 dialogues 中的实际索引
const previewIndex = computed(() => {
  const visible = visibleFloorIndices.value;
  const displayIdx = store.previewDialogueIndex;
  return visible[displayIdx] ?? 0;
});
const previewFloor = computed(() => store.dialogues[previewIndex.value] ?? null);

// Ensure preview floor is parsed when previewing
watch(
  previewFloor,
  async floor => {
    if (floor && !floor.parsed) {
      await store.parseCurrentFloor(previewIndex.value);
    }
  },
  { immediate: true },
);

const historyLines = computed<{ speaker?: string; text: string }[]>(() => {
  const floor = previewFloor.value;
  if (!floor?.blocks?.length) return [];
  return floor.blocks
    .filter((block: MessageBlock) => block.type !== 'user')
    .map((block: MessageBlock) => {
      if (block.type === 'character') {
        return { speaker: block.character, text: block.text ?? '' };
      }
      return { text: block.message ?? '' };
    });
});

function prevPage() {
  const displayIdx = store.previewDialogueIndex;
  if (displayIdx > 0) {
    store.previewDialogueIndex = displayIdx - 1;
  }
}

function nextPage() {
  const displayIdx = store.previewDialogueIndex;
  if (displayIdx < totalFloors.value - 1) {
    store.previewDialogueIndex = displayIdx + 1;
  }
}

function onPageInput(e: Event) {
  const val = parseInt((e.target as HTMLInputElement).value);
  if (!isNaN(val)) {
    store.previewDialogueIndex = Math.max(0, Math.min(val - 1, totalFloors.value - 1));
  }
}

function jumpToFloor() {
  store.navigateFloorTo(previewIndex.value);
  store.setOverlay('none');
}

function goToLine(index: number) {
  // 1. Navigate to this floor
  store.navigateFloorTo(previewIndex.value);
  // 2. Jump to the corresponding block within the floor
  store.currentBlockIndex = index;
  store.setOverlay('none');
}

const panelShellStyle = {
  maxWidth: 'var(--theme-history-panel-shell-max-width, var(--theme-panel-shell-max-width, min(100%, 42rem)))',
  maxHeight: 'var(--theme-history-panel-shell-max-height, var(--theme-panel-shell-max-height, 90%))',
};

const panelStyle: Record<string, string> = {
  width: '100%',
  height: '100%',
  maxHeight: 'var(--theme-panel-max-height, 100%)',
  borderColor: 'var(--theme-panel-border, rgba(90,79,64,0.6))',
  background: 'var(--theme-panel-bg, var(--vn-panel-bg))',
  backdropFilter: 'blur(var(--theme-panel-content-blur, 12px)) saturate(var(--theme-panel-content-saturate, 100%))',
  display: 'flex',
  flexDirection: 'column',
};
const headerBorder = { borderBottom: '1px solid var(--theme-history-header-border, rgba(90,79,64,0.3))' };
const decoTop = {
  height: '3px',
  background: 'linear-gradient(to right, transparent, var(--theme-accent-soft, rgba(139,69,19,0.6)), transparent)',
};
const decoTopThin = {
  height: '1px',
  marginTop: '1px',
  background:
    'linear-gradient(to right, transparent, var(--theme-history-header-border, rgba(139,69,19,0.3)), transparent)',
};
const decoBottomThin = {
  height: '1px',
  background:
    'linear-gradient(to right, transparent, var(--theme-history-header-border, rgba(139,69,19,0.3)), transparent)',
};
const decoBottom = {
  height: '2px',
  marginTop: '1px',
  background: 'linear-gradient(to right, transparent, var(--theme-accent-soft, rgba(139,69,19,0.5)), transparent)',
};
</script>
